name: Jest

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches:
      - main

env:
  WORKING_DIRECTORY: .

jobs:
  build:
    reuns-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.12.1]
    
    steps:
      - uses: actions/checkout@v4

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm

      - name: Install dependencies
        run: npm ci

      - name: Run Jest
        run: npm run test -- --ci --passWithNoTests
